export enum TypeColors {
  grass = 'green',
  water = 'blue',
  normal = 'grey',
  fighting = 'brown',
  flying = 'turquoise',
  ground = 'brown',
  rock = 'tan',
  ghost = 'purple',
  steel = 'grey',
  fire = 'red',
  electric = 'gold',
  bug = 'green',
  psychic = 'purple',
  ice = 'blue',
  dragon = 'orange',
  dark = 'black',
  fairy = 'pink',
  uknknown = 'gray',
  shadow = 'black',
}
